/// Tests for the MP3 reader.
///
/// MP3 is the one format here whose fixtures cannot be generated by the test.
/// A FLAC can be written by hand because a VERBATIM subframe is just the
/// samples; an MPEG layer III encoder is a psychoacoustic model, a hybrid
/// filter bank and a Huffman coder, and writing one in order to test a decoder
/// would mean writing something larger and less trustworthy than the thing
/// under test. Nor can the suite call out to ffmpeg or lame, which are not
/// installed on the build machines and would make the tests skip themselves
/// exactly where they are needed.
///
/// So these two fixtures are checked in -- as base64, which is a third the size
/// of a byte array, stays inside the column limit and keeps the suite one file.
/// They are the smallest files that still prove something: a fifth of a second
/// of stereo and a tenth of a second of mono, encoded from sine waves whose
/// frequency and amplitude are known. Because the signal is known, the tests
/// assert that what comes back IS that signal -- the right amplitude at the
/// encoded frequency, near nothing at every other frequency, and a
/// sample-by-sample comparison against the original -- rather than merely that
/// the decoder did not crash.
///
/// Regenerate with LAME 3.100 via its Python binding (pip install lameenc):
///
///     import lameenc, math, struct, base64
///     def sine(f, n, a, rate=44100):
///         return [a * math.sin(2 * math.pi * f * i / rate) for i in range(n)]
///     def encode(channels, bitrate):
///         e = lameenc.Encoder()
///         e.set_bit_rate(bitrate); e.set_in_sample_rate(44100)
///         e.set_channels(len(channels)); e.set_quality(2)
///         pcm = b"".join(struct.pack("<h", int(round(c[i] * 32767)))
///                        for i in range(len(channels[0])) for c in channels)
///         return base64.b64encode(e.encode(pcm) + e.flush()).decode()
///     encode([sine(1000, 8820, 0.5), sine(3000, 8820, 0.25)], 128)   # stereo
///     encode([sine(1000, 4410, 0.5)], 64)                            # mono

#include <sa/io/AudioFile.h>
#include <sa/io/Mp3Reader.h>
#include <sa/io/PeakPyramid.h>

#include <algorithm>
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <numbers>
#include <random>
#include <span>
#include <string>
#include <string_view>
#include <vector>

using namespace sa;
using namespace sa::io;
using Catch::Approx;

namespace {

/// 0.2 s of 44.1 kHz stereo at 128 kbit/s: 1 kHz at 0.5 on the left, 3 kHz at
/// 0.25 on the right. Different tones per channel on purpose -- a de-interleave
/// bug cannot survive a test that asks each channel which note it is playing.
constexpr std::string_view kStereoTonesMp3 =
    "//uQRAAAAfMM1R08YAA4YsraoKAADFirk/mWoBGUlW+3IUICBmtt2Q9D0PQ9D1Gzw2NDIpfwvwHc"
    "CGCrEzQsRAgAAAAgEAOD4PvwQ4nB/gg6c6fdy/nOn3dPu5c/pBDl/d0oMqAAZbdsMYxjjGMAAAAA"
    "C/u9/+iJyWLigNAFAAAAABQPDHQffqd+f5Tz/Ke/oRkAf4EOcP9Hv6EAFiSZlAEAFAMBQMBQMBwF"
    "Ki73//m3cbW/iOrwLueCy5hmGgPM5+wAogA98J6O4Yb8J8O0YUS3/E+EaC7DtGF/8kTIvF5Eu//j"
    "1Mi8SRiXS7/EQVBURHv9YKiIKgqW/+FQ0WwEAoEAYikgEAoEAoGADZgsi8VsQ3w+ELO+OUKC8WcO"
    "kQl+sPhCaIA4SI9YIUggGpgangRJ0hNwfMILENHN/8ZUmiLEWMS7/+OaTRFiLGJFSK/xEFQVER7/"
    "WCoiCoKlv/hUFRE86tZZTYWABjAsgEUwMAF/MG+BgzBUAKswQYIrMOcGgTJUCYsyXL2pORmTDDGB"
    "Qn8wsQFTMFQBtTA8gH40yMOt//uSRB8P8s8LQ4d/YABiIxhg4PwACMQtEA3/iEGfJ6EAH9JQSDIS"
    "YtGZ5D2Vft//T6fVp1/T//J9fd/fEn0O283/////+Y63y+lSXBMASAIzAOwEAwH8EuMD1BKDBuwP"
    "wwZULqMLpD4DIRSJw+DktZMZ5EyjCXQg4wjMFkMAjAZTAigMcwH0BMDADcwCQAZT5/0f00/yVn/d"
    "6/+Wd+j/p7fs//yIBo3wdMdKDMkU1NSOHlDAwgP0wYMJkMWEtSz5WBuwwugGHODqIzoPwghCIEmC"
    "wYBgKrr/q6///p+3//b/V+3r7/+j9vvPn/9kPDOMNbRMMAJAITAhgEIwmQEKMELAuTAvgAIwCUFR"
    "MHmEPDHgZKU+EtVGMYfD2zCFgbwwR0EFMC6AsDAiQIUDoywN4gACVh7n1//V///ftq/nf6//+//r"
    "Pf3/87/v9PvVm1cv//uEhw2x8wawyUM2cI9+IwLwCPMGPBRjF0GH8/IQOyMMUAwzjZAA0NMcgsAh"
    "kVCBeVrT////9H///9H6/2///TRiSESGIABxpJuNR9X01L1VrP/7kkQpAAIDC0SDX+IQb6yIzwvC"
    "lscQK0Xgv6Lxd6ehgV/SwIuWWNNDqpgUCKYcAHZgwgeGDECaYPwWphZjcGQxy2fskKBjSC7mEGE4"
    "YGgJpgFgQEgAK4kDV7SH///97L/B1j8rZ+Nq3Gyfwb6///2/+N/f/yuv7fiOb//R9OCXyd2FQzAB"
    "J322lkkMUhsDTNgjI+grlkjwMIBOXJQBCtbyS+G5i6IurVt7/q/u1/+2vu6r+n/W7//7vo6n///e"
    "xsZEaNwMnCATALkkDEMtAS+AMqLMDjSVMJ3AEjIUg44/SQIDMa4ANjCTwBMwTAAYMCzAKTAZgD4D"
    "QNAMCdBAAH3//9X//ft//319X//X/6m///Of7f+/VX0q8bQAW9uwjbdSbIleyBYOSPm/CRZhcmh3"
    "MC4sChN1QznOnH9Gcj6Ko/21f+37f2//9X6Or/+jFdneHhSAG/u+nJ5PNQPsjqXQ6LYL8xDyHcMh"
    "UwlhjpzXMFBBKtwIbjFJb5/33/PKcuW6v/lvkeRT4cZp7Lf7+Y//qDpAcuRmSFRl5eAkQw1LMCT/"
    "+5JERIABrgtQaD14zEDDCd8F/KCJzC0ODf+IQaqnoQAvzlCA9DBiwrkxhTUGP+oIHzDQAdg5u4TV"
    "SIM4mcx6OzFQaMHgFKwx/i1dXt/0dv2dW3/R5+v9FlX91N367NnTp10/e6hqWMv8ylDIwAYAnMB7"
    "ARjCPQTYwRQEhME3BKDBwQggws4RVMiDiLj9aU90xs8OmMJYBnTBLQNgwJwBlMA1AAgDKge7AbAi"
    "AVfV1f0f/+3fv/5zq6//+3fvqP///nbNPO3/366uqv/8B0EOjBzKAgBO5ngWY45mASAjBgYYXmYa"
    "txdHHVEWZg4wPwdT0mxQhpamZeRmUAwYPqQ9P///o//9ur2f/6P7/+r871N//+10TElBnw4gBcRg"
    "YqIQG+o0BlVvgUPwG0QSYR0DOGPsn+p9ApJ0Yy2DMmEWAWRgkIDaYFgArGA2gKZ38mo4CQX8X/V/"
    "00/If/f9/+h/6f+nt+3+fyFFK+PLpoYIakXmpSpgGIJwYAkGVmAKeKRhcxKCYAgEMAYLeYGGEABi"
    "kigYlB4EigDhGGUdv7/6/V////uSRGuPAiULRAN/2hBVYxhgV/mwCp2HEA3+qEGKDGJ1X+LA////"
    "2/9f+v1/r/+/+v1f/2///9/f+e/SGTFPAAAq0i+ptbataPWvetSR4tjYDawUSgI3oBqcHAaWKYGg"
    "oSYCCFgGAZrkZh7ZrYYB+E1mAAAhxgAIEmYAUApGALgFZ1GLoKBvl6+tZWXrpkqaei2z+c9f/V/K"
    "f8iptL21//xHQM6UEMqDzQSg1hHN0oTAhwTIwOgMFMM95Ojh0SMcwasH4OG3zJWwQlI0Thh6JDyk"
    "X/6+r//6Ps/bq+j9f7Ov/+K/u9Z//9Q2pVEXST1CogMaD85ZFzSb2NhN06pSTCbQm4x7xKjPhaK0"
    "DGNgfcwiMDUMESAYTAlwBQwEQAIAgA8DABUtU7uv6P+j+S7f7fW7/T/X/09n3/+qo6PnNkBlBiaC"
    "nGyMJzliYG2CYGDUBcJjAOxMfyCQmmGVg7RxxkmfSoYgAYNBBhQHgILKWmOT9tdf//0f/t1+z//Z"
    "bX/dZ0/t28AKQsiAADQLFPp5uEX1dd1XhhgYUBxjkSnLViZ2P//7kkSBjwIuC0QDf9oQVCMYYAef"
    "kglgLQ4N/4hBfYxiOB5+SBkMSmTEIYK2EKmKVJZxzWxXKYhgD2GC0ga5gXAD0YDmApmAlAIBgEQB"
    "IYAqAFl2H79XTX9HRT2//f93+v+r/p7LFfGiAFtrdI03U2qoDnRZE7LEWvF4TDldj0sIRIIl+wqw"
    "IBlYFetdWyy76mL+/u8b7K/+//9Sf//u+nVdndndTAH+12VKto+mj9kfpuwrGRDwKZKuovcFBCYV"
    "5hzeAmCwwja3KO1BA7f30b8L06f379v/BvVV/R9H/DPTztv9/cr/1dLAhC4iHBeDSAYaHJl4emvR"
    "geeIpjDopkf9eBbmGfgBQaWDS4RMlCYwgJAqFSQAPi3////T/2f///////Ff3Cee32EATWSXq+ja"
    "aF+976KCkrxCEwwMvcApGBYAOYZ4YBtIgygYUYWBNJgDlWNPhuYu/9jG22c9d9//p+z/s/vv/U9V"
    "bl1qhUQwATePtpZI45tVR8WDUMglvZeywwurT/ICQvX4/cYBAlrLn+SzkjXX7P9PZ9vXt0fR57//"
    "+5JEngABygrP6D1I3EXGac8LgqKIHC0SDn+KARoMJfQseoLS9tX/9IM8vERDGAP9r9zeJZrXP5+D"
    "dhfkXnXpFAEYPdZy8+AIHsMf+MU4wz/z9n3f6n//+ns+Hv7v/1kpAAAAPH/9ibn6aw1yZaA8DLH0"
    "ZeCQZMJwZMGWrOQxqMCwnAwRlt4PoXfp+l2HlUzTDZ0YTmcJfN12AF3C0iai+zEQDEXo6agaK6x4"
    "HfRYdl9M7DkTkrjdZ23fh+fqOQ5ECSthjLJZQ08vp+4U9v6lQeFgfPlAQEgYE4Xe//Y5tN/qYUdT"
    "zb9mz9vZVtVbdtv+QBP9t5ylNbJZ+wIYln+HAkAAB4PagC6J193Ld+X3P//wqWWaOxDLXQKBmH5Z"
    "9DgZsHFvIFf+3Xt/////+ef6ww5vDDnxuNy+3UjdP9JY5nnqnp7fcKSksV4xLMN09Pm8PikmXD8E"
    "HAhb+t9xR3/4Yrp1wfSoMFHSNQBJIQgGAwIhEDFAwMeEQCAsSAOXmQgwansKMxkBI6855pAcFTQg"
    "vMRlr/AP2AAgBZYHBuAwgDak//uSRNmAAdELUfg8YNw2guoPB4GikbCbQfXcADHxGGi2mbACDOUD"
    "QkQmHdwGhgFIDVA4JHCFg+LxAwW+BjAAIYNljGiURCpef4pcPUHAThsQBEyIsQIxJ38cAlMUGMmJ"
    "0Jw0JlKiovE1/MiKE4M2OeRMghogYl0x0VJF7/nCAE4M2OeRMghoxgRQxLpdrRSLxeRR/+Tg55Fy"
    "fJxpgTBUIORc3Jxka0VF4vAqdBURf4gd/8sBIBABIhILYOC/P+jgBl4vD/gYaG6JoED/hoAXTDAw"
    "AIAxB4GBgcBhQTAYFBQgKLM4GGgEBn1vgfUAoAQgABBgGJCmAwZAMUjBXCgDAEAAWKAYFAYAQDAc"
    "AQMCAEGyRyi38OnC5gZgnDYgBdIcKCD4hyRcv5EBZYucg4zBOIC5TJZdMiBDnf0iYKhByLk+TiDF"
    "EipFVLRMi8Rb/qJgqEHIuT5OIVFwxLpdrRSLxeRR/+aEXL5uXGoFw0J8vm5pRrRUZF5aKNaKkv//"
    "QQQ////MlgpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqv/7kkTbAAY5WtA+cmAA0c6p9cxU"
    "AEAAAaQcAAAgAAA0g4AABKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqo=";

/// 0.1 s of 44.1 kHz mono at 64 kbit/s: 1 kHz at 0.5. Mono is not stereo with
/// one channel as far as the decode path is concerned, so it gets its own file.
constexpr std::string_view kMonoToneMp3 =
    "//tQxAAABsgnXPTAgCG5oGkbOSAAACFfbJcvXr169fe7aypXBMAcAMCYjn6KAgCBiD4f4IcTg/wQ"
    "dOdPu5fznT7un3cuf0ghy/u6QBAIEIIMMAaCDBYS3v9mIxwYiIegCbPAJDPGPoxONDDMvJAEeRaR"
    "h8BgEWBwvg2qJuEFvw+IckXKLl/xjhQQhYhouX/xzSkRYixiXf/yKmRFiLGJdLv/+ZF4vIl0upJJ"
    "f//ol0ug0FQVEX/wqGiywQAAI+23sEn5f+C9XRYi/K8QAFTFQv/7UsQLAAeIK0W9xIAxGIWiAb/x"
    "CNMWb030dAgRp8spigUApF6ndWz6/MvrWIRDv9/s37f//1v7f//6P/8iAaN8HTHSgzJFNTUjh5Qw"
    "MID9MGDCZDFhLUs+VgbsMLoBhzg6iM6D8IIQiBJgsGAYCq6/6uv//6ft//2/1ft6+//o/bX/+4SH"
    "DbHzBrDJQzZwj34jAvAI8wY8FGMXQYfz8hA7IwxQDDONkADQ0xyCwCGRUIF5WtP////0f///0fr/"
    "b//9P/9wsIB1GWFwggmVaHbZ//tSxCeDyAwtEg1/iEEGBaJBr/EIGBcADYsGfGMPBOR/3QCOYaAA"
    "DHLwaaYDBk0VmExKCAsOgF6Gf6///o////p////6eS/c//0SuH2+YVBh6lVwpyMCcAVjBfQUExbp"
    "omPveD9TDDAN44+aTShGMqj8xCKzBwULPtY17////d/r///+z93//3fT3CpOCMAaMCJAIzAcQSUw"
    "XUDvMBZAtTBFgKAwkwV6MdAGBjGEsNA+f46jMKCGJDENgnAwngJCMEKADjAJo+qcNSSBpIMf4tX/"
    "+1LERIPIPC8SDP+IQW0FocK/sADV//JO2/Z1bf9Hvr/KWVd3dT/7NlWJBgIdLyevaCQWCsWADDNI"
    "RAI0ldvhU4HBDc7YZbifHatY7v4WAJivKBNwsIAOMSmbEyQgnwZcLTwFAEoB8ozwauK5EyYPCAAY"
    "zJ83FzEyOaOayfIKKDGTD4A1YQ4c4ZYmSK/lQi5FyuRQuEVSSSq/kQGbIubk4ggktEupF4vf8+qm"
    "X0y4XDRaKKkkv/8vl83LhcQN01v/hUFhAhMwBKJt1y/FxkZPe//7UsRTgBNFI2W5qRAZDIalN5hg"
    "BCYiKhkkmh6mEq5yYrBQCRUcSpQNB2IjuVDZUNKBpQNPKnSpiDUO8S/q9Hyx6j//6es6VOwah1VM"
    "QU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
    "VVVVVVVVVVVVVVVVVVVVVVVV";

constexpr double kStereoDurationFrames = 8820.0;
constexpr double kMonoDurationFrames = 4410.0;

/// An MPEG frame carries 1152 samples, and an encoder's filter bank runs ahead
/// of the stream, so a decode is longer than what was encoded: a delay at the
/// front and padding at the back, neither of which these fixtures can declare
/// because a LAME/Xing header is only written when the encoder can seek back
/// over its own output, and these were encoded straight to memory. Two MPEG
/// frames is the slack that costs.
constexpr SampleCount kCodecSlackFrames = 2 * 1152;

std::vector<std::byte> fromBase64(std::string_view text) {
    const auto valueOf = [](char symbol) -> int {
        if (symbol >= 'A' && symbol <= 'Z') {
            return symbol - 'A';
        }
        if (symbol >= 'a' && symbol <= 'z') {
            return symbol - 'a' + 26;
        }
        if (symbol >= '0' && symbol <= '9') {
            return symbol - '0' + 52;
        }
        if (symbol == '+') {
            return 62;
        }
        if (symbol == '/') {
            return 63;
        }
        return -1;
    };

    std::vector<std::byte> bytes;
    bytes.reserve(text.size() * 3 / 4);
    std::uint32_t accumulator = 0;
    int bits = 0;
    for (char symbol : text) {
        const int value = valueOf(symbol);
        if (value < 0) {
            continue; // padding
        }
        accumulator = (accumulator << 6) | static_cast<std::uint32_t>(value);
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            bytes.push_back(static_cast<std::byte>((accumulator >> bits) & 0xFFu));
        }
    }
    return bytes;
}

/// Amplitude of `frequency` in a block of samples, by the Goertzel algorithm.
///
/// A single-bin DFT, which is all this needs: the question a lossy decode has
/// to answer is "is the tone that was encoded still there, at the level it went
/// in at, and is anything else there that should not be".
double toneAmplitude(const float* samples, SampleCount count, double frequency, SampleRate rate) {
    const double omega = 2.0 * std::numbers::pi * frequency / rate.hz();
    const double coefficient = 2.0 * std::cos(omega);
    double previous = 0.0;
    double beforeThat = 0.0;
    for (SampleCount i = 0; i < count; ++i) {
        const double current =
            static_cast<double>(samples[i]) + coefficient * previous - beforeThat;
        beforeThat = previous;
        previous = current;
    }
    const double real = previous - beforeThat * std::cos(omega);
    const double imaginary = beforeThat * std::sin(omega);
    return 2.0 * std::sqrt(real * real + imaginary * imaginary) / static_cast<double>(count);
}

/// The smallest root-mean-square difference between the decode and the sine it
/// was made from, over every plausible alignment.
///
/// The alignment has to be searched rather than assumed. An encoder's delay is
/// a property of the encoder, and without a LAME header in the file the decoder
/// has no way to know it and no business guessing -- so the samples come back
/// correct but shifted, and a comparison that ignored that would fail on a
/// perfectly good decode.
double bestAlignedError(const float* samples, SampleCount count, double frequency, double amplitude,
                        SampleRate rate) {
    constexpr SampleCount kSearchFrames = 2000;
    constexpr SampleCount kCompareFrames = 4000;
    REQUIRE(count > kSearchFrames + kCompareFrames);

    double best = 1.0e9;
    for (SampleCount offset = 0; offset < kSearchFrames; ++offset) {
        double sum = 0.0;
        for (SampleCount i = 0; i < kCompareFrames; ++i) {
            const double wanted = amplitude * std::sin(2.0 * std::numbers::pi * frequency *
                                                       static_cast<double>(i) / rate.hz());
            const double difference = static_cast<double>(samples[offset + i]) - wanted;
            sum += difference * difference;
        }
        best = std::min(best, std::sqrt(sum / static_cast<double>(kCompareFrames)));
    }
    return best;
}

/// An ID3v2.3 tag, as an encoder would put in front of the audio.
///
/// Built here rather than baked into the fixture so that the same bytes can be
/// decoded with and without it, which is the only way to show the tag was
/// stepped over rather than decoded as audio.
std::vector<std::byte> id3v2Tag(std::uint32_t bodyBytes) {
    std::vector<std::byte> tag{std::byte{'I'}, std::byte{'D'}, std::byte{'3'},
                               std::byte{3},   std::byte{0},   std::byte{0}};
    // The size is "syncsafe": seven bits per byte, so that no byte of it can
    // look like a frame sync.
    for (int shift = 21; shift >= 0; shift -= 7) {
        tag.push_back(static_cast<std::byte>((bodyBytes >> shift) & 0x7Fu));
    }
    tag.resize(tag.size() + bodyBytes, std::byte{0});
    return tag;
}

std::vector<std::byte> concatenated(std::span<const std::byte> first,
                                    std::span<const std::byte> second) {
    std::vector<std::byte> joined{first.begin(), first.end()};
    joined.insert(joined.end(), second.begin(), second.end());
    return joined;
}

/// Parse and, if that worked, decode too. As in the FLAC tests, every caller
/// keeps its bytes in a named local: Mp3Reader::fromMemory does not copy.
void parseAndRead(std::span<const std::byte> bytes) {
    auto reader = Mp3Reader::fromMemory(bytes);
    if (!reader) {
        return;
    }
    AudioBuffer destination{ChannelLayout::stereo(), 512};
    (void)reader.value().read(0, destination.view());
    (void)reader.value().read(reader.value().info().frameCount / 2, destination.view());
    (void)reader.value().read(reader.value().info().frameCount - 1, destination.view());
    (void)reader.value().readAll();
}

class ScopedFile {
public:
    explicit ScopedFile(std::string name)
        : path_(std::filesystem::temp_directory_path() / std::move(name)) {}

    ~ScopedFile() {
        std::error_code ignored;
        std::filesystem::remove(path_, ignored);
    }

    ScopedFile(const ScopedFile&) = delete;
    ScopedFile& operator=(const ScopedFile&) = delete;

    [[nodiscard]] const std::filesystem::path& path() const noexcept { return path_; }

    void write(std::span<const std::byte> bytes) const {
        std::ofstream stream{path_, std::ios::binary | std::ios::trunc};
        stream.write(reinterpret_cast<const char*>(bytes.data()),
                     static_cast<std::streamsize>(bytes.size()));
    }

private:
    std::filesystem::path path_;
};

} // namespace

TEST_CASE("An MP3 decodes to the tones that were encoded", "[io][mp3]") {
    const auto bytes = fromBase64(kStereoTonesMp3);
    auto reader = Mp3Reader::fromMemory(bytes);
    REQUIRE(reader.hasValue());

    const AudioFileInfo& info = reader.value().info();
    CHECK(info.sampleRate == kSampleRate44100);
    CHECK(info.channelCount() == 2);
    CHECK(info.format == SampleFormat::Float32);
    // Longer than what went in, by the codec's own delay and padding.
    CHECK(info.frameCount >= static_cast<SampleCount>(kStereoDurationFrames));
    CHECK(info.frameCount <= static_cast<SampleCount>(kStereoDurationFrames) + kCodecSlackFrames);

    auto decoded = reader.value().readAll();
    REQUIRE(decoded.hasValue());
    REQUIRE(decoded.value().frames() == info.frameCount);

    // Measure over the steady middle: the first and last few milliseconds are
    // the encoder's ramp, and no codec reproduces those faithfully.
    const SampleCount start = info.frameCount / 4;
    const SampleCount length = info.frameCount / 2;

    const double leftAtOneKilohertz =
        toneAmplitude(decoded.value().channel(0) + start, length, 1000.0, info.sampleRate);
    const double leftAtThreeKilohertz =
        toneAmplitude(decoded.value().channel(0) + start, length, 3000.0, info.sampleRate);
    const double rightAtThreeKilohertz =
        toneAmplitude(decoded.value().channel(1) + start, length, 3000.0, info.sampleRate);
    const double rightAtOneKilohertz =
        toneAmplitude(decoded.value().channel(1) + start, length, 1000.0, info.sampleRate);

    INFO("left 1 kHz " << leftAtOneKilohertz << ", left 3 kHz " << leftAtThreeKilohertz
                       << ", right 3 kHz " << rightAtThreeKilohertz << ", right 1 kHz "
                       << rightAtOneKilohertz);

    // Each channel plays its own note at the level it was given, within the
    // few per cent a lossy codec moves it.
    CHECK(leftAtOneKilohertz == Approx(0.5).epsilon(0.1));
    CHECK(rightAtThreeKilohertz == Approx(0.25).epsilon(0.1));

    // And not the other channel's note. Thirty decibels down is a weak claim
    // against the sixty-odd actually measured, and a de-interleave bug would
    // put the two within a factor of one.
    CHECK(leftAtThreeKilohertz < 0.25 / 31.6);
    CHECK(rightAtOneKilohertz < 0.5 / 31.6);
}

TEST_CASE("The decoded samples follow the encoded waveform", "[io][mp3]") {
    // Frequency content alone would pass a decode that was right in the
    // spectrum and wrong in time. This compares sample against sample.
    const auto bytes = fromBase64(kStereoTonesMp3);
    auto reader = Mp3Reader::fromMemory(bytes);
    REQUIRE(reader.hasValue());
    const SampleRate rate = reader.value().info().sampleRate;

    auto decoded = reader.value().readAll();
    REQUIRE(decoded.hasValue());

    const double leftError =
        bestAlignedError(decoded.value().channel(0), decoded.value().frames(), 1000.0, 0.5, rate);
    const double rightError =
        bestAlignedError(decoded.value().channel(1), decoded.value().frames(), 3000.0, 0.25, rate);
    INFO("root-mean-square error: left " << leftError << " against an amplitude of 0.5, right "
                                         << rightError << " against 0.25");
    // Measured at 0.018 and 0.009 for this fixture. A decode that was merely
    // tone-shaped rather than the same tone would sit an order of magnitude
    // above this -- two sines a quarter-cycle apart differ by 0.7 of their
    // amplitude.
    CHECK(leftError < 0.03);
    CHECK(rightError < 0.03);
}

TEST_CASE("Mono MP3 decodes to one channel of the right tone", "[io][mp3]") {
    const auto bytes = fromBase64(kMonoToneMp3);
    auto reader = Mp3Reader::fromMemory(bytes);
    REQUIRE(reader.hasValue());

    const AudioFileInfo& info = reader.value().info();
    CHECK(info.channelCount() == 1);
    CHECK(info.sampleRate == kSampleRate44100);
    CHECK(info.frameCount >= static_cast<SampleCount>(kMonoDurationFrames));
    CHECK(info.frameCount <= static_cast<SampleCount>(kMonoDurationFrames) + kCodecSlackFrames);

    auto decoded = reader.value().readAll();
    REQUIRE(decoded.hasValue());
    const SampleCount start = info.frameCount / 4;
    CHECK(toneAmplitude(decoded.value().channel(0) + start, info.frameCount / 2, 1000.0,
                        info.sampleRate) == Approx(0.5).epsilon(0.1));
}

TEST_CASE("Reading an MP3 from an arbitrary frame matches reading from the start", "[io][mp3]") {
    // Seeking in an MP3 is a rescan, not an index lookup, and a frame decoded
    // after a seek depends on the frames before it. Getting the same samples
    // either way is the property that makes random access usable at all.
    const auto bytes = fromBase64(kStereoTonesMp3);
    auto reader = Mp3Reader::fromMemory(bytes);
    REQUIRE(reader.hasValue());

    auto whole = reader.value().readAll();
    REQUIRE(whole.hasValue());
    const SampleCount total = whole.value().frames();

    for (SampleIndex start : {SampleIndex{0}, SampleIndex{1}, SampleIndex{1151}, SampleIndex{1152},
                              SampleIndex{5000}, SampleIndex{2304}, SampleIndex{100}}) {
        INFO("from frame " << start);
        AudioBuffer piece{ChannelLayout::stereo(), 300};
        auto got = reader.value().read(start, piece.view());
        REQUIRE(got.hasValue());
        REQUIRE(got.value() == std::min<SampleCount>(300, total - start));

        SampleCount mismatches = 0;
        for (int channel = 0; channel < 2; ++channel) {
            for (SampleCount i = 0; i < got.value(); ++i) {
                if (piece.channel(channel)[i] != whole.value().channel(channel)[start + i]) {
                    ++mismatches;
                }
            }
        }
        CHECK(mismatches == 0);
    }
}

TEST_CASE("An ID3v2 tag in front of the audio is stepped over", "[io][mp3]") {
    // Most MP3s in the wild start with one, often kilobytes of it, and a
    // decoder that read it as audio would produce a burst of noise before the
    // first note.
    const auto plain = fromBase64(kMonoToneMp3);
    const auto tagged = concatenated(id3v2Tag(2048), plain);

    CHECK(detectFormat(std::span{tagged}) == ContainerFormat::Mp3);

    auto bare = Mp3Reader::fromMemory(plain);
    auto withTag = Mp3Reader::fromMemory(tagged);
    REQUIRE(bare.hasValue());
    REQUIRE(withTag.hasValue());
    REQUIRE(bare.value().info().frameCount == withTag.value().info().frameCount);

    auto bareAudio = bare.value().readAll();
    auto taggedAudio = withTag.value().readAll();
    REQUIRE(bareAudio.hasValue());
    REQUIRE(taggedAudio.hasValue());

    SampleCount mismatches = 0;
    for (SampleCount i = 0; i < bareAudio.value().frames(); ++i) {
        if (bareAudio.value().channel(0)[i] != taggedAudio.value().channel(0)[i]) {
            ++mismatches;
        }
    }
    CHECK(mismatches == 0);
}

TEST_CASE("An ID3v1 tag after the audio is not decoded", "[io][mp3]") {
    // The other end of the same problem: 128 bytes of text bolted onto the end
    // of the file. dr_mp3 finds it by seeking backwards from the end, which is
    // the only thing that exercises that arm of the seek callback.
    const auto plain = fromBase64(kMonoToneMp3);
    std::vector<std::byte> trailer{std::byte{'T'}, std::byte{'A'}, std::byte{'G'}};
    trailer.resize(128, std::byte{' '});
    const auto tagged = concatenated(plain, trailer);

    auto reader = Mp3Reader::fromMemory(tagged);
    REQUIRE(reader.hasValue());
    auto decoded = reader.value().readAll();
    REQUIRE(decoded.hasValue());

    const SampleCount start = reader.value().info().frameCount / 4;
    CHECK(toneAmplitude(decoded.value().channel(0) + start, reader.value().info().frameCount / 2,
                        1000.0, reader.value().info().sampleRate) == Approx(0.5).epsilon(0.1));
}

TEST_CASE("An MP3 decode fills only the channels the destination has", "[io][mp3]") {
    const auto bytes = fromBase64(kStereoTonesMp3);
    auto reader = Mp3Reader::fromMemory(bytes);
    REQUIRE(reader.hasValue());

    auto whole = reader.value().readAll();
    REQUIRE(whole.hasValue());

    AudioBuffer mono{ChannelLayout::mono(), 200};
    auto got = reader.value().read(0, mono.view());
    REQUIRE(got.hasValue());
    CHECK(got.value() == 200);
    CHECK(mono.channel(0)[199] == whole.value().channel(0)[199]);

    AudioBuffer wide{ChannelLayout::discrete(4), 200};
    for (int channel = 0; channel < 4; ++channel) {
        wide.channel(channel)[0] = -7.0f;
    }
    got = reader.value().read(0, wide.view());
    REQUIRE(got.hasValue());
    CHECK(wide.channel(1)[0] == whole.value().channel(1)[0]);
    CHECK(wide.channel(2)[0] == -7.0f);
    CHECK(wide.channel(3)[0] == -7.0f);
}

TEST_CASE("Reads outside an MP3 are refused or short, never invented", "[io][mp3]") {
    const auto bytes = fromBase64(kMonoToneMp3);
    auto reader = Mp3Reader::fromMemory(bytes);
    REQUIRE(reader.hasValue());
    const SampleCount total = reader.value().info().frameCount;

    AudioBuffer destination{ChannelLayout::mono(), 64};

    auto negative = reader.value().read(-1, destination.view());
    REQUIRE_FALSE(negative.hasValue());
    CHECK(negative.error().code() == ErrorCode::OutOfRange);

    auto past = reader.value().read(total, destination.view());
    REQUIRE(past.hasValue());
    CHECK(past.value() == 0);

    auto straddling = reader.value().read(total - 10, destination.view());
    REQUIRE(straddling.hasValue());
    CHECK(straddling.value() == 10);
}

TEST_CASE("Input with no MPEG audio in it is rejected", "[io][mp3][robustness]") {
    const std::vector<std::byte> empty;
    CHECK_FALSE(Mp3Reader::fromMemory(empty).hasValue());

    const std::vector<std::byte> junk(4096, std::byte{0x5A});
    CHECK_FALSE(Mp3Reader::fromMemory(junk).hasValue());

    // A tag and nothing behind it. Detection says MP3, which is the right guess
    // from an ID3v2 header; the decoder is what establishes there is no audio.
    const auto tagOnly = id3v2Tag(512);
    CHECK(detectFormat(std::span{tagOnly}) == ContainerFormat::Mp3);
    auto reader = Mp3Reader::fromMemory(tagOnly);
    REQUIRE_FALSE(reader.hasValue());
    CHECK(reader.error().code() == ErrorCode::CorruptData);
}

TEST_CASE("A Xing header claiming an absurd length cannot be trusted", "[io][mp3][robustness]") {
    // An MP3 states its length, if at all, in a Xing header inside the first
    // frame, and that header is part of the file like everything else. This one
    // claims four billion frames. Believing it would make readAll() ask for
    // forty terabytes, and the honest answer to that is not an exception thrown
    // out of a module that reports failure by return.
    const auto plain = fromBase64(kMonoToneMp3);
    auto reader = Mp3Reader::fromMemory(plain);
    REQUIRE(reader.hasValue());
    const SampleCount plainFrames = reader.value().info().frameCount;

    // Overwrite the first frame's body with a Xing tag. For MPEG 1 mono the
    // side information is 17 bytes, so the tag starts 21 bytes into the frame:
    // the identifier, then a flag word whose low bit says a frame count
    // follows, then the count itself.
    auto lying = plain;
    constexpr std::size_t kFrameBytes = 144 * 64000 / 44100;
    REQUIRE(lying.size() > kFrameBytes);
    std::fill(lying.begin() + 4, lying.begin() + static_cast<std::ptrdiff_t>(kFrameBytes),
              std::byte{0});
    const char* identifier = "Xing";
    for (std::size_t i = 0; i < 4; ++i) {
        lying[21 + i] = static_cast<std::byte>(identifier[i]);
    }
    lying[28] = std::byte{0x01};
    for (std::size_t i = 29; i < 33; ++i) {
        lying[i] = std::byte{0xFF};
    }

    auto liar = Mp3Reader::fromMemory(lying);
    REQUIRE(liar.hasValue());

    // The length now comes from measuring the stream, not from the header, so
    // it is something a file of this size could actually hold -- at most
    // thirty-two frames a byte, which is already generous against the densest
    // legal encoding.
    const SampleCount measured = liar.value().info().frameCount;
    INFO("measured " << measured << " frames against " << plainFrames << " untagged");
    CHECK(measured > 0);
    CHECK(measured <= static_cast<SampleCount>(lying.size()) * 32);

    // Shorter than the untagged file, because a Xing frame carries no audio and
    // is skipped rather than decoded. That is also what proves the tag was read
    // at all, rather than this test quietly asserting nothing.
    CHECK(measured < plainFrames);

    auto whole = liar.value().readAll();
    REQUIRE(whole.hasValue());
    CHECK(whole.value().frames() == liar.value().info().frameCount);
}

TEST_CASE("An MP3 truncated at every offset never crashes or hangs", "[io][mp3][robustness]") {
    // Worth little without ASan and worth a great deal with it: this is a C
    // decoder being fed files that stop in the middle of a Huffman codeword.
    const auto complete = fromBase64(kMonoToneMp3);

    for (std::size_t length = 0; length < complete.size(); ++length) {
        const std::vector<std::byte> truncated{
            complete.begin(), complete.begin() + static_cast<std::ptrdiff_t>(length)};
        INFO("truncated to " << length << " of " << complete.size() << " bytes");
        parseAndRead(truncated);
    }
    SUCCEED("every truncation terminated");
}

TEST_CASE("Corrupted MP3 bytes are survived", "[io][mp3][robustness]") {
    const auto complete = fromBase64(kMonoToneMp3);

    std::mt19937 generator{20240918u};
    std::uniform_int_distribution<std::size_t> offset{0, complete.size() - 1};
    std::uniform_int_distribution<int> value{0, 255};

    for (int attempt = 0; attempt < 400; ++attempt) {
        auto mutated = complete;
        for (int flip = 0; flip < 4; ++flip) {
            mutated[offset(generator)] = static_cast<std::byte>(value(generator));
        }
        INFO("attempt " << attempt);
        parseAndRead(mutated);
    }
    SUCCEED("every mutation terminated");
}

TEST_CASE("openAudioFile recognises an MP3 by content", "[io][mp3][format]") {
    // Named .aiff on purpose: detection reads the bytes, never the extension.
    const ScopedFile file{"sa-mp3-by-content.aiff"};
    const auto bytes = fromBase64(kStereoTonesMp3);
    file.write(bytes);

    auto detected = detectFormat(file.path());
    REQUIRE(detected.hasValue());
    CHECK(detected.value() == ContainerFormat::Mp3);
    CHECK(toString(ContainerFormat::Mp3) == "MP3");

    auto opened = openAudioFile(file.path());
    REQUIRE(opened.hasValue());
    const AudioSource& audio = *opened.value();
    CHECK(audio.info().channelCount() == 2);
    CHECK(audio.info().sampleRate == kSampleRate44100);

    AudioBuffer decoded{ChannelLayout::stereo(), audio.info().frameCount};
    auto got = audio.read(0, decoded.view());
    REQUIRE(got.hasValue());
    CHECK(got.value() == audio.info().frameCount);

    const SampleCount start = audio.info().frameCount / 4;
    CHECK(toneAmplitude(decoded.channel(0) + start, audio.info().frameCount / 2, 1000.0,
                        audio.info().sampleRate) == Approx(0.5).epsilon(0.1));
}

TEST_CASE("An MP3 drives the streaming peak pyramid", "[io][mp3][peaks]") {
    // As for FLAC, but the stakes are higher here: a backwards seek in an MP3
    // costs a rescan of the stream, so a reader that seeked on every block
    // would still pass this test and take quadratic time doing it. What is
    // being checked is agreement; what makes it quick is that read() does not
    // seek when it is already in the right place.
    const auto bytes = fromBase64(kStereoTonesMp3);
    auto reader = Mp3Reader::fromMemory(bytes);
    REQUIRE(reader.hasValue());
    auto whole = reader.value().readAll();
    REQUIRE(whole.hasValue());

    auto inMemory = PeakPyramid::build(whole.value().constView());
    auto streamed = PeakPyramid::buildStreaming(reader.value());
    REQUIRE(inMemory.hasValue());
    REQUIRE(streamed.hasValue());

    REQUIRE(streamed.value().levelCount() == inMemory.value().levelCount());
    REQUIRE(streamed.value().sourceFrames() == inMemory.value().sourceFrames());
    SampleCount mismatches = 0;
    for (int level = 0; level < inMemory.value().levelCount(); ++level) {
        REQUIRE(streamed.value().frameCountAt(level) == inMemory.value().frameCountAt(level));
        for (int channel = 0; channel < inMemory.value().channelCount(); ++channel) {
            for (SampleCount f = 0; f < inMemory.value().frameCountAt(level); ++f) {
                const PeakFrame& expected = inMemory.value().frameAt(level, channel, f);
                const PeakFrame& actual = streamed.value().frameAt(level, channel, f);
                if (actual.minimum != expected.minimum || actual.maximum != expected.maximum) {
                    ++mismatches;
                }
            }
        }
    }
    CHECK(mismatches == 0);
}
